name: myapp
description: A Helm chart template for Kubernetes charts repository
version: 0.0.5
home: https://k8s.community/
sources:
  - https://github.com/m033i/myapp
maintainers:
  - name: Kubernetes Community
    email: k8s.community@gmail.com
engine: gotpl
